#!/bin/bash

# BASIC INFO
HOSTNAME=$(hostname)
USERNAME=$(whoami)
TIME=$(date)

# OS INFO
source /etc/os-release
OS="$PRETTY_NAME"

# UPTIME
UPTIME=$(uptime -p)

# OUTPUT
echo "----------------------"
echo "System Report for $HOSTNAME generated by $USERNAME, on $TIME"
echo ""
echo "System Information"
echo "----------------------------"
echo "OS: $OS"
echo "Uptime: $UPTIME"
