#!/bin/bash

# BASIC INFO
HOSTNAME=$(hostname)
USERNAME=$(whoami)
TIME=$(date)

# OS INFO
source /etc/os-release
OS="$PRETTY_NAME"

# UPTIME
UPTIME=$(uptime -p)

# CPU INFO
CPU=$(grep -m1 "model name" /proc/cpuinfo | awk -F: '{print $2}')

# RAM INFO
RAM=$(free -h | awk '/Mem:/ {print $2}')

# DISK SIZE
DISK=$(lsblk -d -o NAME,MODEL,SIZE)

# VIDEO INFO
VIDEO=$(lshw -C display)

# IP ADDRESS
IP=$(hostname -I)

# GATEWAY
GATEWAY=$(ip route | grep default | awk '{print $3}')

# DNS SERVER
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')

# USERS
USER=$(who | awk '{print $1}' | uniq)

# DISK SPACE
Disk_Space=$(df -h --output=target,avail | tail -n +2 | paste -sd " | " -)
# OUTPUT
echo ""
echo "System Report for $HOSTNAME generated by $USERNAME, on $TIME"
echo ""
echo "System Information"
echo "------------------"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "DISK: $DISK"
echo "VIDEO: $VIDEO"
echo "IP= $IP"
echo "GATEWAY= $GATEWAY"
echo "DNS= $DNS"
echo ""
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged IN: $USER "
echo "Disk Space: $Disk_Space"
echo "Process Count:"
echo "Load Average:"
echo "Listening Network Ports:"
echo "UFW Status:"
